### ISSUE TITLE
pio-mainnet-1-archive docker node sync issue

### ISSUE THREAD

**Issue by sawyerru** [provenance-io/mainnet#21]
## Summary of Bug

I am trying to start a docker container with the provenance node, as found [here](https://hub.docker.com/r/provenanceio/node). In the docs simply running the container triggers the node to sync and connect to the network. However, at a certain blockheight the upgrade required is not found.

```bash
8:20PM INF ABCI Replay Blocks appHeight=351999 module=consensus stateHeight=351999 storeHeight=352000
8:20PM INF Replay last block using real app module=consensus
8:20PM ERR UPGRADE "bluetiful" NEEDED at height: 352000: https://github.com/provenance-io/provenance/releases/download/v1.3.0/plan-v1.3.0.json
panic: UPGRADE "bluetiful" NEEDED at height: 352000: https://github.com/provenance-io/provenance/releases/download/v1.3.0/plan-v1.3.0.json
```
## Version

`docker pull provenanceio/node:pio-mainnet-1-archive`
Digest: `8d5af0941f05`

## Steps to Reproduce
`docker run --name my-node -d -v $(pwd)/mynode:/home/provenance provenanceio/node:pio-mainnet-1-archive`

Issue occurs around: `INF ABCI Replay Blocks appHeight=351999 module=consensus stateHeight=351999 storeHeight=352000`
Block height 351999.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by arnabmitra** [comment]
yeah i believe the intent of that  pio-mainnet-1-archive  docker image was to start getting synced with all the genesis info etc, but when you hit an upgrade https://explorer.provenance.io/network/upgrades you will https://hub.docker.com/r/provenanceio/provenance/tags have to select the appropriate tag to run with the same mounted volume.. i think hence the pio-mainnet-1  https://raw.githubusercontent.com/provenance-io/mainnet/main/docker/node/visor/Dockerfile uses cosmovisor which should download the required images at each upgrade..you could even get the latest data folder from here https://provenance.io/quicksync and replace it in the mounted volume and skip to latest imo

**Comment by arnabmitra** [comment]
yeah i believe the intent of that  pio-mainnet-1-archive  docker image was to start getting synced  from height 0 with all the genesis info/configs  etc, but when you hit an upgrade https://explorer.provenance.io/network/upgrades you will https://hub.docker.com/r/provenanceio/provenance/tags have to select the appropriate tag to run with the same mounted volume.. i think hence the intent of the pio-mainnet-1 tag ,  https://raw.githubusercontent.com/provenance-io/mainnet/main/docker/node/visor/Dockerfile was to replace the ^^ with  cosmovisor which should download the required images at each upgrade..you could even get the latest data folder from here https://provenance.io/quicksync and replace it in the mounted volume and skip to latest tag imo...

**Comment by arnabmitra** [comment]
> thanks @arnabmitra for the info. I have tried running the following `docker pull provenanceio/provenance:v1.3.1` then tried to start the node via `provenanced init && provenanced start`. Is this the process you are alluding to by your comment or is there a better way via cosmovisor?

Sorry for the late reply, you can run provenanced as a docker image too if you want 
To run the provenanced via docker 
Step 1: docker run -it --rm --name my-node -v $(pwd)/mynode:/home/provenance provenanceio/node:pio-mainnet-1
This will create all Note: The directory ./mynode will contain all data, configs, and binaries related to this chain id. (you can name the folder obv whatever you want)
Step 2: After the docker logs show progress with catching up stop the docker container
Step3: download https://tools.highstakes.ch/provenance_snapshot the latest snaphot from that site 
Step 4: Unzip download from Step 3, and place it in the mynode folder(delete/ backup the existing `data` folder) 
Step 4: docker run --rm -it -v $(pwd)/mynode:/home/provenance provenanceio/provenance:v1.11.1 provenanced start
you should see it catching like below ```06PM INF executed block height=6578785 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B3132392031323720313735203232332031373520393820373820313431203637203230392031303720343120313031203233352032313020313139203132352037302031333320313030203231382034362035382033312031312035362031343020313836203235332032323820323137203138305D3A3634363236317D
10:06PM INF committed state app_hash=817FAFDFAF624E8D43D16B2965EBD2777D468564DA2E3A1F0B388CBAFDE4D9B4 height=6578785 module=state num_txs=0
10:06PM INF indexed block height=6578785 module=txindex
10:06PM INF executed block height=6578786 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B323233203133392031363720343620393420373920313035203136392031343620332037322036352033342032333520383320313820313820313220393720313933203336203230392031343820313630203232203234302037342031343320323438203532203137203135315D3A3634363236327D
10:06PM INF committed state app_hash=DF8BA72E5E4F69A99203484122EB5312120C61C124D194A016F04A8FF8341197 height=6578786 module=state num_txs=0
10:06PM INF indexed block height=6578786 module=txindex
10:06PM INF executed block height=6578787 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B31323520313637203135352031393820313730203135392031353020323138203737203120313937203139312031363120313034203232332031203133362031353220353420323534203231362032323120313732203134203230322031393620313234203136203231203132352039362034335D3A3634363236337D
10:06PM INF committed state app_hash=7DA79BC6AA9F96DA4D01C5BFA168DF01889836FED8DDAC0ECAC47C10157D602B height=6578787 module=state num_txs=0
10:06PM INF indexed block height=6578787 module=txindex
10:06PM INF executed block height=6578788 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B33372031392037203137302031333320313636203736203133332031343920313534203231332039322033322033312032323420313138203132302032323520313434203133302032333620313420323334203434203020313831203131382031353920363520323520323235203231375D3A3634363236347D
10:06PM INF committed state app_hash=251307AA85A64C85959AD55C201FE07678E19082EC0EEA2C00B5769F4119E1D9 height=6578788 module=state num_txs=0
10:06PM INF indexed block height=6578788 module=txindex
10:06PM INF executed block height=6578789 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B31353420323533203137322031353820323320373120363720323720333620313630203233332032343520343120373320343920333320313635203132312032303920313836203732203234372031363120313439203132203733203234203833203234203136302038352033365D3A3634363236357D
10:06PM INF committed state app_hash=9AFDAC9E1747431B24A0E9F529493121A579D1BA48F7A1950C49185318A05524 height=6578789 module=state num_txs=0
10:06PM INF indexed block height=6578789 module=txindex
10:06PM INF executed block height=6578790 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B3235312032333720313432203134302032343720313539203138372037372037392031373720313336203131382032313020313431203338203735203835203134203235203430203630203136372031362032333720343820313630203136312039312038362031373920313831203130345D3A3634363236367D
10:06PM INF committed state app_hash=FBED8E8CF79FBB4D4FB18876D28D264B550E19283CA710ED30A0A15B56B3B568 height=6578790 module=state num_txs=0
10:06PM INF indexed block height=6578790 module=txindex
10:06PM INF executed block height=6578791 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B353120313431203138332032303620313234203234203935203130372032302035302031353520333820313434203337203132362031373520323130203135342033312032333720372039352031383220353620313731203133203835203233342031323520383120313732203132365D3A3634363236377D
10:06PM INF committed state app_hash=338DB7CE7C185F6B14329B2690257EAFD29A1FED075FB638AB0D55EA7D51AC7E height=6578791 module=state num_txs=0
10:06PM INF indexed block height=6578791 module=txindex
10:06PM INF executed block height=6578792 module=state num_invalid_txs=0 num_valid_txs=0
10:06PM INF commit synced commit=436F6D6D697449447B5B3837203433203930203632203520313331203136203130382039342031383220313435203334203230382038392031313220323533203139302031343220313031203320313235203133203336203233203234342031373120313932203135392032343520313435203138203133325D3A3634363236387D
10:06PM INF committed state app_hash=572B5A3E0583106C5EB6```

**Comment by debasish22** [comment]
Thanks @arnabmitra for the snapshot approach . We are up and running now with the provenancd as a docker image and able to run queries against the provenanced daemon. we wanted to get the transactions for any given address but did not find any such method . Can you please help us with this .

**Comment by arnabmitra** [comment]
> Thanks @arnabmitra for the snapshot approach . We are up and running now with the provenancd as a docker image and able to run queries against the provenanced daemon. we wanted to get the transactions for any given address but did not find any such method . Can you please help us with this .

tx's on the blockchain are typically aggregated over blocks ..see https://explorer.provenance.io/accounts/pb1xvd4k9jg5h0d4dhzr4z0txtwe9p5zxf58xcmxd as n example app that does it.. you can use websockets to read and filter the tx's you want for an address

**Comment by arnabmitra** [comment]
Since you are up and running on the node front i am going to close this issue, if you have more questions please create issue on the https://github.com/provenance-io/provenance project which is better monitored than this project.
