### ISSUE TITLE
Nhash does not have metadata with denom units

### ISSUE THREAD

**Issue by leeduan** [provenance-io/mainnet#4]
## Nhash does not have metadata with denom units

`nhash` marker does not have any metadata details. To be able to correctly display and use `nhash` as intended, we need a `hash` denom unit with 10^9 exponent

## 1.0

This is not related to a specific version since it's data-specific.

## Steps to Reproduce

```
  // DenomsMetadata queries the client metadata of a given coin denomination.
  rpc DenomMetadata(QueryDenomMetadataRequest) returns (QueryDenomMetadataResponse) {
    option (google.api.http).get = "/cosmos/bank/v1beta1/denoms_metadata/{denom}";
  }
```

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by SpicyLemon** [comment]
The bank module's denom-metadata query returns this entry for nhash:

```json
    {
      "description": "Hash is the staking token of the Provenance Blockchain",
      "denom_units": [
        {
          "denom": "nhash",
          "exponent": 0,
          "aliases": []
        },
        {
          "denom": "hash",
          "exponent": 9,
          "aliases": []
        }
      ],
      "base": "nhash",
      "display": "hash",
      "name": "Hash",
      "symbol": "HASH",
      "uri": "",
      "uri_hash": ""
    }
```

I'm not sure when it was added, but it does have an entry for `hash` now.
